<?php

/**
 * @file Easy social module.
 */
/**
 * Easy Social Widget Type constants
 */
define('EASY_SOCIAL_WIDGET_HORIZONTAL', 0);
define('EASY_SOCIAL_WIDGET_VERTICAL', 1);

/**
 * Easy Social max number of blocks
 */
define('EASY_SOCIAL_BLOCK_MAX', 10);

module_load_include('inc', 'easy_social', 'easy_social.widgets');

/**
 * Implements hook_permission().
 */
function easy_social_permission() {
  return array(
    'administer easy social' => array(
      'title' => t('Administer Easy Social'),
      'description' => t('Manage Easy Social permissions.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function easy_social_menu() {
  $items = array();

  $items['admin/config/content/easy_social'] = array(
    'title' => 'Easy Social Settings',
    'description' => 'Configure the social buttons and node types',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_easy_social_admin_config_main'),
    'access arguments' => array('administer easy social'),
    'file' => 'easy_social.admin.inc',
  );

  $items['admin/config/content/easy_social/default'] = array(
    'title' => 'Easy Social Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'easy_social.admin.inc',
  );

  $items['admin/config/content/easy_social/paths-ignore'] = array(
    'title' => 'Ignore Paths',
    'description' => 'Global paths to ignore and do not display Easy Social',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_easy_social_admin_config_ignore_paths'),
    'access arguments' => array('administer easy social'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'easy_social.admin.inc',
    'weight' => 1,
  );

  $items['admin/config/content/easy_social/widget-extra'] = array(
    'title' => 'Extra Widget Settings',
    'description' => 'Extra settings for widgets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_easy_social_admin_config_extra'),
    'access arguments' => array('administer easy social'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'easy_social.admin.inc',
    'weight' => 2,
  );

  $items['admin/config/content/easy_social/widget-extra/default'] = array(
    'title' => 'Extra Widget Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/content/easy_social/widget-extra/twitter'] = array(
    'title' => 'Twitter',
    'description' => 'Extra settings for Twitter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_easy_social_admin_config_extra_twitter'),
    'access arguments' => array('administer easy social'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'easy_social.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_variable_info().
 */
function easy_social_variable_info() {

  // global settings
  $variables['easy_social_ignore_paths'] = array(
    'title' => t('Easy Social Global Ignore Paths'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_global_type'] = array(
    'title' => t('Easy Social Global Type of Buttons'),
    'default' => 1,
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_global_widgets'] = array(
    'title' => t('Easy Social Global Type of Network Buttons'),
    'default' => array('twitter', 'facebook', 'googleplus', 'linkedin'),
    'group' => 'easy_social',
    'token' => FALSE,
  );

  // custom settings per content type
  $node_types = node_type_get_types();

  foreach ($node_types as $type => $typeobj) {
    $variables["easy_social_{$type}_enable"] = array(
      'title' => t('Enable Easy Social for nodes of type %type', array('%type' => $typeobj->name)),
      'default' => FALSE,
      'group' => 'easy_social',
      'token' => FALSE,
    );

    $variables["easy_social_{$type}_count"] = array(
      'title' => t('Number of Easy Social fields for nodes of type %type', array('%type' => $typeobj->name)),
      'default' => 1,
      'group' => 'easy_social',
      'token' => FALSE,
    );

    $variables["easy_social_{$type}_type"] = array(
      'title' => t('Easy Social widget type for nodes of %type', array('%type' => $typeobj->name)),
      'default' => 1,
      'group' => 'easy_social',
      'token' => FALSE,
    );

    $variables["easy_social_{$type}_widgets"] = array(
      'title' => t('Easy Social widgets for nodes of %type', array('%type' => $typeobj->name)),
      'default' => array(),
      'group' => 'easy_social',
      'token' => FALSE,
    );
  }

  // custom settings for blocks
  $variables['easy_social_block_count'] = array(
    'title' => t('Number of Easy Social blocks'),
    'default' => 1,
    'group' => 'easy_social',
    'token' => FALSE,
  );

  // this is done like this because calling variable_get_value() inside here = WSOD
  for ($i = 1; $i <= EASY_SOCIAL_BLOCK_MAX; ++$i) {
    $variables["easy_social_block_{$i}_title"] = array(
      'title' => t('Block title'),
      'default' => '',
      'group' => 'easy_social',
      'token' => FALSE,
    );

    $variables["easy_social_block_{$i}_override"] = array(
      'title' => t('Override settings for this block'),
      'default' => FALSE,
      'group' => 'easy_social',
      'token' => FALSE,
    );

    $variables["easy_social_block_{$i}_type"] = array(
      'title' => t('Widget Type'),
      'default' => 1,
      'group' => 'easy_social',
      'token' => FALSE,
    );

    $variables["easy_social_block_{$i}_widgets"] = array(
      'title' => t('Enabled Widgets'),
      'default' => array(),
      'group' => 'easy_social',
      'token' => FALSE,
    );
  }

  // custom settings for Twitter
  $variables['easy_social_twitter_account_via'] = array(
    'title' => t('Easy Social Global Mention Account'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_twitter_account_related'] = array(
    'title' => t('Easy Social Global Related Account'),
    'default' => '',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  $variables['easy_social_twitter_account_description'] = array(
    'title' => t('Easy Social Global Twitter Description'),
    'default' => 'Check it out!',
    'group' => 'easy_social',
    'token' => FALSE,
  );

  return $variables;
}

/**
 * Implements hook_theme().
 */
function easy_social_theme() {
  $theme = array(
    'easy_social_links' => array(
      'template' => 'easy-social-links',
      'variables' => array('social_links' => array()),
    ),
  );
  return $theme;
}

/**
 * Implements hook_field_extra_fields().
 * The Easy Social available in Manage display page in the content types
 */
function easy_social_field_extra_fields() {
  $extra = array();
  $node_types = node_type_get_types();

  foreach ($node_types as $type => $typeobj) {
    if (variable_get_value("easy_social_{$type}_enable")) {
      for ($i = 1, $num = variable_get_value("easy_social_{$type}_count"); $i <= $num; ++$i) {
        if (isset($extra['node'][$type]['display'])) {
          $extra['node'][$type]['display']["easy_social_{$i}"] = array(
            'label' => t('Easy Social !num', array('!num' => $i)),
            'weight' => 100 + $i,
          );
        }
        else {
          $extra['node'][$type] = array(
            'display' => array(
              "easy_social_{$i}" => array(
                'label' => t('Easy Social !num', array('!num' => $i)),
                'weight' => 100 + $i,
              ),
            ),
          );
        }
      }
    }
  }
  return $extra;
}

/**
 * Implements hook_node_view().
 * Certify to load the buttons in the moment I want
 */
function easy_social_node_view($node, $view_mode, $langcode) {
  // we use this instead of $node->path to get an absolute URL
  $url = url('node/' . $node->nid, array('absolute' => TRUE));

  // check if easy social is enabled for this content type
  if (variable_get_value("easy_social_{$node->type}_enable")) {
    $type = variable_get_value("easy_social_{$node->type}_type");
    $enabled_widgets = variable_get_value("easy_social_{$node->type}_widgets");
    $widgets = _easy_social_render_widgets($url, $node->title, $type, $enabled_widgets);
    $count = variable_get_value("easy_social_{$node->type}_count");

    // add as many extra fields as we've defined
    for ($i = 1; $i <= $count; ++$i) {
      $node->content["easy_social_{$i}"] = array(
        '#theme' => 'easy_social_links',
        '#social_links' => $widgets,
        '#weight' => 100 + $i,
      );
    }
  }
}

/**
 * Returns a list of enabled social widgets
 * Results are cached
 * 
 * @return array
 */
function easy_social_get_widgets() {
  static $static;

  // first check static cache
  if (!isset($static)) {
    // then check Drupal's cache
    $cache = cache_get('easy_social_widgets');

    if (isset($cache->data) && is_array($cache->data)) {
      $return = $cache->data;
    }
    else {
      $return = array();

      foreach (module_implements('easy_social_widget') as $name) {
        $widgets = module_invoke($name, 'easy_social_widget');
        $return = array_merge($return, $widgets);
      }

      cache_set('easy_social_widgets', $return, 'bin', CACHE_TEMPORARY);
    }
    $static = $return;
  }

  return $static;
}

/**
 * Implements hook_easy_social_widgets().
 */
function easy_social_easy_social_widget() {
  return array(
    'facebook' => array(
      'name' => 'Facebook',
      'markup' => '_easy_social_widget_facebook_markup',
      'script' => 'http://static.ak.fbcdn.net/connect.php/js/FB.Share',
    ),
    'googleplus' => array(
      'name' => 'Google+',
      'markup' => '_easy_social_widget_googleplus_markup',
      'script' => 'https://apis.google.com/js/plusone.js',
    ),
    'linkedin' => array(
      'name' => 'LinkedIn',
      'markup' => '_easy_social_widget_linkedin_markup',
      'script' => 'http://platform.linkedin.com/in.js',
    ),
    'twitter' => array(
      'name' => 'Twitter',
      'markup' => '_easy_social_widget_twitter_markup',
      'script' => 'http://platform.twitter.com/widgets.js',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function easy_social_block_info() {
  $return = array();
  $num_blocks = variable_get_value('easy_social_block_count');

  for ($i = 1; $i <= $num_blocks; ++$i) {
    $return["easy_social_block_{$i}"] = array(
      'info' => t('Easy Social Block !num', array('!num' => $i)),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    );
  }

  return $return;
}

/**
 * Implements hook_block_view().
 */
function easy_social_block_view($delta = '') {
  $num_blocks = variable_get_value('easy_social_block_count');

  // use current page' url and title
  $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
  $url = url($path, array('absolute' => TRUE));
  $title = drupal_get_title();

  for ($i = 1; $i <= $num_blocks; ++$i) {
    if ($delta === "easy_social_block_{$i}") {
      // check if this block has overriden settings
      if (variable_get_value("easy_social_block_{$i}_override")) {
        $type = variable_get_value("easy_social_block_{$i}_type");
        $enabled_widgets = variable_get_value("easy_social_block_{$i}_widgets");
      }
      else {
        $type = $enabled_widgets = NULL;
      }

      $widgets = _easy_social_render_widgets($url, $title, $type, $enabled_widgets);

      return array(
        'subject' => variable_get_value("easy_social_block_{$i}_title"),
        'content' => array(
          '#theme' => 'easy_social_links',
          '#social_links' => $widgets,
        ),
      );
    }
  }
}

/**
 * Returns whether easy_social is to ignored in the current page
 * 
 * @return bool
 */
function _easy_social_page_ignore() {
  // Check if the path is ignored
  $urls_ignored = variable_get_value('easy_social_ignore_paths');

  $page_match = FALSE;

  $path = drupal_get_path_alias($_GET['q']);

  // Compare with the internal and path alias (if any).
  $page_match = drupal_match_path($path, $urls_ignored);

  if ($path != $_GET['q']) {
    $page_match = $page_match || drupal_match_path($_GET['q'], $urls_ignored);
  }

  return $page_match;
}

/**
 * 
 * 
 * @param string $url
 * @param string $title 
 * @param int $type
 * @param string $enabled_widgets
 * @return array
 */
function _easy_social_render_widgets($url, $title, $type = NULL, $enabled_widgets = NULL) {
  if (!_easy_social_page_ignore()) {
    // fallback to default settings
    if (!isset($type)) {
      $type = variable_get_value('easy_social_global_type');
    }

    if (!isset($enabled_widgets)) {
      $enabled_widgets = variable_get_value('easy_social_global_widgets');
    }

    $social_links = array();
    $widgets = easy_social_get_widgets();

    //Load Js files and generate respective markups
    foreach ($enabled_widgets as $service) {
      // add external javascript, if any
      if (isset($widgets[$service]['script'])) {
        drupal_add_js($widgets[$service]['script'], 'external');
      }

      // add widget markup
      if (isset($widgets[$service]['markup'])) {
        $social_links[$service] = call_user_func($widgets[$service]['markup'], $url, $type, $title);
      }
    }
    return $social_links;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds easy social options to the node type form.
 */
function easy_social_form_node_type_form_alter(&$form, $form_state) {
  $type = $form['#node_type'];
  $options = _easy_social_get_options();
  $form['#submit'][] = 'easy_social_node_type_form_submit';

  $form['easy_social'] = array(
    '#type' => 'fieldset',
    '#title' => t('Easy Social settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
  );

  $form['easy_social']["easy_social_{$type->type}_enable"] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Easy Social'),
    '#description' => t('Check this option to enable easy social for this content type'),
    '#default_value' => variable_get_value("easy_social_{$type->type}_enable"),
  );

  $form['easy_social']["easy_social_{$type->type}_count"] = array(
    '#type' => 'select',
    '#title' => t('Number of Easy Social fields'),
    '#description' => t('You can add more than one Easy Social field to your nodes. This is useful, for example, to add the widget both at top and at the bottom of a node.'),
    '#options' => array('1' => 1, '2' => 2),
    '#default_value' => variable_get_value("easy_social_{$type->type}_count"),
  );

  $form['easy_social']["easy_social_{$type->type}_type"] = array(
    '#type' => 'radios',
    '#title' => t('Type of buttons'),
    '#options' => array(
      EASY_SOCIAL_WIDGET_HORIZONTAL => t('Horizontal'),
      EASY_SOCIAL_WIDGET_VERTICAL => t('Vertical')
    ),
    '#default_value' => variable_get_value("easy_social_{$type->type}_type")
  );

  $form['easy_social']["easy_social_{$type->type}_widgets"] = array(
    '#type' => 'checkboxes',
    '#title' => t('Social Widgets'),
    '#options' => $options,
    '#default_value' => variable_get_value("easy_social_{$type->type}_widgets"),
  );
}

/**
 * Submit callback
 * 
 * @see easy_social_form_node_type_form_alter().
 */
function easy_social_node_type_form_submit(&$form, &$form_state) {
  foreach ($form_state['values'] as $name => $value) {
    if (strpos($name, 'easy_social') === 0) {
      variable_set($name, $value);
    }
  }
}

/**
 * Returns easy social options for use in settings forms
 * 
 * @return array
 */
function _easy_social_get_options() {
  static $options;

  if (!isset($options)) {
    $widgets = easy_social_get_widgets();
    $options = array();

    foreach ($widgets as $k => $widget) {
      $options[$k] = isset($widget['name']) ? $widget['name'] : $k;
    }
  }

  return $options;
}